<?php
/**
 * @copyright Copyright (c) 2023 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

/**
 * @var Magebit\PageListWidget\Block\Widget\PageList $block
 * @var Magento\Framework\Escaper $escaper
 * @var array $pageData
 */

$pageData = $this->getPages();

?>

<p><strong><?= $escaper->escapeHtml($block->getData('title')) ?></strong></p>
<ul>
    <?php foreach ($pageData as $title => $url): ?>
        <li>
            <a href="<?= $escaper->escapeUrl($this->getUrl($url)) ?>"><?= $escaper->escapeHtml($title) ?></a>
        </li>
    <?php endforeach; ?>
</ul>
